services:
  postgres:
    image: postgres:16.4-alpine
    container_name: postgres_go_1M
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # Optional: uncomment the next line if you have a seed.sql file in an init-db folder
      # - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: go_event_app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # We override the .env DATABASE_URL here to use the Docker internal hostname 'postgres'
      - DATABASE_URL=host=postgres user=postgres password=postgres dbname=events port=5432 sslmode=disable
    restart: always

volumes:
  postgres-data:
